name: Publish jvm-getter to crates.io

on:
  release:
    types: [created]

jobs:
  publish:
    name: Publish jvm-getter to crates.io
    runs-on: ubuntu-latest
    steps:
      - name: Check out the main branch
        uses: actions/checkout@v4

      - name: Set up credentials before publishing
        run: cargo login ${CRATES_IO_API_TOKEN}
        env:
          CRATES_IO_API_TOKEN: ${{ secrets.CRATES_IO_API_TOKEN }}

      - name: Run checks before publishing
        run: cargo publish --dry-run
        working-directory: jvm-getter
        env:
          RUSTFLAGS: "-D warnings"

      - name: Publish jvm-getter to crates.io
        run: cargo publish
        working-directory: jvm-getter
        env:
          RUSTFLAGS: "-D warnings"
